M48
; DRILL file {KiCad 9.0.6+1} date 2025-12-08T12:46:46+0000
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2025-12-08T12:46:46+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X128518Y-85119
X128518Y-90899
T2
X151925Y-98119
M30
